[build-system]
requires = [
    "setuptools", "wheel",
    'oldest-supported-numpy; python_version >= "3.5"',
    'numpy==1.16.6; python_version == "3.4" or python_version == "2.7"',
    'numpy == 1.11.3; python_version == "3.3" or python_version == "3.2" or python_version == "2.6"',
    'cython >= 0.29, <3.0; python_version >= "2.6" and python_version <= 3.4 and python_version != "3.2"',
    'cython >= 0.26, < 0.27; python_version == "3.2"',
    'cython >= 0.29, <3.1; python_version >= "3.5"'
]
build-backend = "setuptools.build_meta"
