name: basemap-for-windows

env:
  PKGDIR: "packages/basemap"

on:
  push:
    paths:
      - ".github/workflows/basemap-for-windows.yml"
      - "packages/basemap/**"
  pull_request:
    paths:
      - ".github/workflows/basemap-for-windows.yml"
      - "packages/basemap/**"
  workflow_dispatch:

jobs:

  checkout:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Upload checkout
        uses: actions/upload-artifact@v1
        with:
          name: checkout
          path: .

  build-geos:
    strategy:
      matrix:
        include:
          - 
            arch: "x64"
            msvc-toolset: "14.16"
            cmake-version: "3.14.7"
          - 
            arch: "x86"
            msvc-toolset: "14.16"
            cmake-version: "3.13.2"
          - 
            arch: "x64"
            msvc-toolset: "9.0"
            cmake-version: "3.14.7"
          - 
            arch: "x86"
            msvc-toolset: "9.0"
            cmake-version: "3.13.2"
      max-parallel: 4
      fail-fast: false
    needs: checkout
    runs-on: windows-latest
    steps:
      -
        name: Download checkout
        uses: actions/download-artifact@v1
        with:
          name: checkout
          path: .
      -
        name: Set Python
        uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.arch }}
          python-version: "3.6"
      -
        name: Setup MSVC toolset
        uses: pylegacy/actions/setup-msvc@v1
        with:
          architecture: ${{ matrix.arch }}
          version: ${{ matrix.msvc-toolset }}
      -
        name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: ${{ matrix.cmake-version }}
      -
        name: Build GEOS from source
        run: |
          cd ${{ env.PKGDIR }}
          python -c "import utils; utils.GeosLibrary('3.5.1').build('extern', njobs=16)"
      -
        name: Upload GEOS artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts-geos-${{ matrix.arch }}-msvc${{ matrix.msvc-toolset }}
          path: ${{ env.PKGDIR }}/extern

  build:
    strategy:
      matrix:
        arch:
          ["x64", "x86"]
        python-version:
          ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
      max-parallel: 3
      fail-fast: false
    needs: build-geos
    runs-on: windows-latest
    steps:
      -
        name: Download checkout
        uses: actions/download-artifact@v1
        with:
          name: checkout
          path: .
      -
        name: Set Python
        uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.arch }}
          python-version: ${{ matrix.python-version }}
      -
        name: Set MSVC toolset version
        run: |
          if ("${{ matrix.python-version }}" -eq "2.7") {
              echo "msvc-toolset=9.0" >> $env:GITHUB_ENV
          } else {
              echo "msvc-toolset=14.16" >> $env:GITHUB_ENV
          }
      -
        name: Setup MSVC toolset
        uses: pylegacy/actions/setup-msvc@v1
        with:
          architecture: ${{ matrix.arch }}
          version: ${{ env.msvc-toolset }}
      -
        name: Install Python base packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
      -
        name: Generate NumPy headers
        run: |
          if ("${{ matrix.python-version }}" -In "2.6", "3.2", "3.3") {
              Set-Variable -Name "pkgvers" -Value "1.11.3"
          } elseif ("${{ matrix.python-version }}" -In "2.7", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9") {
              Set-Variable -Name "pkgvers" -Value "1.16.6"
          } else {
              Set-Variable -Name "pkgvers" -Value "1.21.4"
          }
          Set-Variable -Name "pkgname" -Value "numpy"
          Set-Variable -Name "pkgcode" -Value "numpy-${pkgvers}"
          Set-Variable -Name "includedir" -Value "numpy/core/include"
          python -m pip install cython
          python -m pip download --no-binary=numpy "numpy == ${pkgvers}"
          tar -xf "${pkgcode}.zip"
          rm "${pkgcode}.zip"
          cd "${pkgcode}"
          python setup.py build
          cp -R build/src.*/${includedir}/numpy/*.h ${includedir}/numpy
          cd ..
          cp -R "${pkgcode}/${includedir}/numpy" "${{ env.PKGDIR }}/extern/include/numpy"
          rm -r "${pkgcode}"
      -
        name: Download GEOS artifacts
        uses: actions/download-artifact@v1
        with:
          name: artifacts-geos-${{ matrix.arch }}-msvc${{ env.msvc-toolset }}
          path: ${{ env.PKGDIR }}/extern
      -
        name: Build wheel
        run: |
          cd ${{ env.PKGDIR }}
          $env:GEOS_DIR = "$env:GITHUB_WORKSPACE/${{ env.PKGDIR }}/extern"
          $env:NUMPY_INCLUDE_PATH = "$env:GITHUB_WORKSPACE/${{ env.PKGDIR }}/extern/include"
          $env:SETUPTOOLS_USE_DISTUTILS = "stdlib"
          pip install -r requirements-setup.txt
          python setup.py sdist
          pip wheel -w dist --no-deps (Get-Item dist/*.zip)
      -
        name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts-build-${{ matrix.arch }}-${{ matrix.python-version }}
          path: ${{ env.PKGDIR }}/dist

  test:
    strategy:
      matrix:
        arch:
          ["x64", "x86"]
        python-version:
          ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
      max-parallel: 3
      fail-fast: false
    needs: build
    runs-on: windows-latest
    steps:
      -
        name: Download checkout
        uses: actions/download-artifact@v1
        with:
          name: checkout
          path: .
      -
        name: Set Python
        uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.arch }}
          python-version: ${{ matrix.python-version }}
      -
        name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: artifacts-build-${{ matrix.arch }}-${{ matrix.python-version }}
          path: ${{ env.PKGDIR }}/dist
      -
        name: Install package
        run: |
          pip install --prefer-binary (Get-Item ${{ env.PKGDIR }}/dist/*-win*.whl)
      -
        name: Test package
        run: |
          python -c "from mpl_toolkits.basemap import Basemap"

  upload:
    strategy:
      matrix:
        arch:
          ["x64", "x86"]
        python-version:
          ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10"]
      max-parallel: 1
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: test
    runs-on: windows-latest
    environment: PyPI
    steps:
      -
        name: Set Python
        uses: actions/setup-python@v2
        with:
          architecture: ${{ matrix.arch }}
          python-version: ${{ matrix.python-version }}
      -
        name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
          name: artifacts-build-${{ matrix.arch }}-${{ matrix.python-version }}
          path: ${{ env.PKGDIR }}/dist
      -
        name: Install requirements
        run: |
          pip install --prefer-binary twine
      -
        name: Upload distributables
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
          TWINE_REPOSITORY_URL: "${{ secrets.PYPI_REPOSITORY_URL }}"
        run: |
          python -m twine check                                               `
              ${{ env.PKGDIR }}/dist/*.zip                                    `
              ${{ env.PKGDIR }}/dist/*.whl
          python -m twine upload --skip-existing                              `
              ${{ env.PKGDIR }}/dist/*.whl
